import { Component } from '@angular/core';

@Component({
    selector: 'ngx-dashboard',
    styleUrls: [ './dashboard.component.scss' ],
    templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
    calls = [
        {
            sourceSite: 'hitta.se',
            sourceAd: 'googleads',
            sourceCampaign: 'campaign 01',
            callRequest: '/ny-kund/abcdef',
            type: 'Future',
            createdAt: '21/01/2020 05:06:58 pm',
            plannedAt: '21/01/2020 05:06:58 pm',
            value: 1000,
            rating: 'Good',
            operatorName: 'Marcus Zimmermann',
            operatorPhone: '+4671234567',
            clientPhone: '+4677654321',
            talkTimeMin: 1,
            talkTimeSec: 24,
            oatSec: 24,
            record: '...',
        },
        {
            sourceSite: 'hitta.se',
            sourceAd: 'googleads',
            sourceCampaign: 'campaign 01',
            callRequest: '/ny-kund/abcdef',
            type: 'Future',
            createdAt: '21/01/2020 05:06:58 pm',
            value: 1000,
            rating: 'Good',
            operatorName: 'Marcus Zimmermann',
            operatorPhone: '+4671234567',
            clientPhone: '+4677654321',
            talkTimeMin: 1,
            talkTimeSec: 24,
            oatSec: 24,
            record: '...',
        },
        {
            sourceSite: 'hitta.se',
            sourceAd: 'googleads',
            sourceCampaign: 'campaign 01',
            callRequest: '/ny-kund/abcdef',
            type: 'Future',
            createdAt: '21/01/2020 05:06:58 pm',
            value: 23500,
            rating: 'Good',
            operatorName: 'Marcus Zimmermann',
            operatorPhone: '+4671234567',
            clientPhone: '+4677654321',
            talkTimeMin: 1,
            talkTimeSec: 24,
            oatSec: 24,
            record: '...',
        },
        {
            sourceSite: 'hitta.se',
            sourceAd: 'googleads',
            sourceCampaign: 'campaign 01',
            callRequest: '/ny-kund/abcdef',
            type: 'Future',
            createdAt: '21/01/2020 05:06:58 pm',
            value: 23500,
            rating: 'Good',
            operatorName: 'Marcus Zimmermann',
            operatorPhone: '+4671234567',
            clientPhone: '+4677654321',
            talkTimeMin: 1,
            talkTimeSec: 24,
            oatSec: 24,
            record: '...',
        },
    ];
}
